server:
  servlet:
    context-path: /studio-ghibli/api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studio_ghibli # Conexão com o banco de dados
    username: postgres
    password: postgres
  jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         "[format_sql]": true
     show-sql: true
     hibernate:
      ddl-auto: none # Desabilita a auto-criação do hibernate (cria as tabelas com base nas entities)
  main:
    banner-mode: off # Desabilita o banner do spring no output